### PR TITLE
Added a dictionary of constants

### PR DESCRIPTION
**Pull request by ckjbgames**
Implements all constants on the "Constants" wiki page as their own dictionary.

### CODE REVIEW

**Comment by Mr-Xcoder** [comment]
Those are not unnecessary constants! Think about it. Cthulhu is Prefix. If you were to write `39+1`, without a constant you'd write it as `+39 1`, but with a constant you'd write it as `+39O`.

**Comment by ckjbgames** [comment]
It just seemed that way

**Comment by ckjbgames** [comment]
Didn't realize that there didn't have to be a space between one of those constants and another value.

**Comment by Mr-Xcoder** [comment]
It's ok

**Pull request merged**
